# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
# language: en_core_web_md

# pipeline:
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   # - name: WhitespaceTokenizer
#   # - name: RegexFeaturizer
#   # - name: LexicalSyntacticFeaturizer
#   # - name: CountVectorsFeaturizer
#   # - name: CountVectorsFeaturizer
#   #   analyzer: char_wb
#   - name: SpacyNLP
#     model: "en_core_web_md"
#   - name: SpacyTokenizer
#   - name: SpacyFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: RegexFeaturizer
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   # - name: ResponseSelector
#   #   epochs: 100

# # Configuration for Rasa Core.
# # https://rasa.com/docs/rasa/core/policies/
# policies:
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100

# language: en
# pipeline:
#   - name: HFTransformersNLP
#     model_name: "gpt2"
#     model_weights: "gpt2"
#   - name: LanguageModelTokenizer
#   - name: LanguageModelFeaturizer
#   - name: DIETClassifier
#     epochs: 200

# pipeline:
#  - name: SpacyNLP
#    case_sensitive: 1
#    model: de_pytt_bertbasecased_lg_gnad
#  - name: SpacyTokenizer
#  - name: SpacyFeaturizer
#  - name: SklearnIntentClassifier

# policies:
#  - name: KerasPolicy
#    batch_size: 50
#    epochs: 200
#    max_training_samples: 300
#  - name: MemoizationPolicy
#    max_history: 5
#  - name: FormPolicy
#  - name: MappingPolicy

# language: en
# pipeline:
#   - name: ConveRTTokenizer
#   - name: WhitespaceTokenizer
#   - name: ConveRTFeaturizer
#   - name: EmbeddingIntentClassifier
#   - name: DIETClassifier
#     epochs: 200

language: en_core_web_md

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
