# Generated by Django 2.2 on 2021-03-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assistant_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=1024)),
                ('assistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_assistant_api.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_sentence', models.CharField(max_length=4096)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_assistant_api.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='IntentExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_sentence', models.CharField(max_length=2048)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_assistant_api.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=64)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_assistant_api.Collective')),
            ],
        ),
        migrations.AddField(
            model_name='assistant',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_assistant_api.Channel'),
        ),
    ]
